#Makefile needed to compile matrix library
#Created by Alejandro Ciuba

CC = gcc
CCFLAGS = -Wall

all: matrix_utility matrix_ops

matrix_utility: matrix_utility.c
	$(CC) $(CCFLAGS) -c matrix_utility.c

matrix_ops: matrix_ops.c
	$(CC) $(CCFLAGS) -c matrix_ops.c